# Generated by Django 4.2.2 on 2023-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(verbose_name='movie_image')),
                ('category', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Science fiction', 'Science fiction'), ('Documentary', 'Documentary'), ('Cartoon', 'Cartoon')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
